apiVersion: v1 
kind: Namespace
metadata: 
  name: benefits-env
---
apiVersion: v1
kind: Deployment
metadata:
  name: app-api
  namespace: benefits-env
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: benefits-api
    spec:
      containers:
      - name: benefits-api
        # image: CONTAINER_REGISTER_BASE_URI
        ports:
          - name:  benefits-api
            containerPort:  8086
            protocol: TCP
        resource:
          request:
            cpu: 256m
            memory: 512Mi
          limit:           
---
apiVersion: v1
kind: Service
metadata:
  name: svc-benefits-api
  namespace: benefits-env
spec:
  ports:
    - port: 80 #egress port 
      targetPort: 8086 #ingress port ~ containerPort
  selector:
    app: benefits-api
  type: ClusterIP
