apiVersion: v1 
kind: Namespace
metadata: 
  name: benefits-env
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api
  namespace: benefits-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benefits-api
  template:
    metadata:
      labels:
        app: benefits-api
    spec:
      containers:
      - name: benefits-api
        image: CONTAINER_REGISTRY_BASE_URI
        ports:
          - name: benefits-api
            containerPort: 8086
            protocol: TCP
        resources:
          requests:
            cpu: "256m"
            memory: "512Mi"
          limits:
            cpu: "512m"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: svc-benefits-api
  namespace: benefits-env
spec:
  ports:
    - port: 80     # egress port 
      targetPort: 8086  # ingress port (containerPort)
  selector:
    app: benefits-api
  type: ClusterIP
