apiVersion: v1 
kind: Namespace
metadata: 
  name: benefits-env
---
apiVersion: v1
kind: Deployment
metadata:
  name: app-api
  namespace: benefits-env
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend-api
        image: CONTAINER_REGISTER_BASE_URI
        ports:
          - name:  backend-api
            containerPort:  8086
            protocol: TCP
        resource:
          request:
            cpu: 256m
            memory: 512Mi
          limit:
