apiVersion: v1 
kind: Namespace
metadata: 
  name: benefits-env
---
apiVersion: v1
kind: Deployment
metadata:
  name: app-api
  namespace: benefits-env
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: backend-api
        image: CONTAINER_REGISTER_BASE_URI
        ports:
          - name:  backend-api
            containerPort:  8086
            protocol: TCP
        resource:
          request:
            cpu: 256m
            memory: 512Mi
          limit:
---
# https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: benefits-ingress
  namespace: benefits-env
spec:
  rules:
  - host: foo.bar.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ServiceName
            port:
              number: 80