apiVersion: v2
name: monitoring
description: A Helm Chart for deploying Prometheus, Grafana, Loki, and Alertmanager for monitoring and logging.
type: application
version: 0.1.0
appVersion: "1.0"
maintainers:
  - name: fledxy
    email: trinhbao2000@gmail.com
keywords:
  - monitoring
  - prometheus
  - grafana
  - loki
  - alertmanager
