apiVersion: v2
name: monitoring
description: Grafana, Loki and Fluent Bit monitoring stack
version: 0.1.0
type: application
appVersion: "1.0.0"
maintainers:
  - name: Fledxy
    email: fledxy@gmail.com
keywords:
  - monitoring
  - logging
  - grafana
  - loki
  - fluent-bit
dependencies:
  - name: grafana
    version: "7.0.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: grafana.enabled
  - name: loki
    version: "5.0.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: loki.enabled
