apiVersion: v2
name: monitoring
description: Monitoring stack (Prometheus, Grafana, Loki, Alertmanager)
version: 0.1.0
dependencies:
  - name: grafana
    version: "7.3.9"
    repository: "https://grafana.github.io/helm-charts"
