apiVersion: v1
global:
  image:
    repository: grafana/grafana
    tag: "latest"
prometheus:
  enabled: true
  image:
    repository: prom/prometheus
    tag: "latest"
  service:
    type: ClusterIP
    port: 9090
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
grafana:
  enabled: true
  admin:
    user: admin
    password: admin
  service:
    type: ClusterIP
    port: 3000
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
loki:
  enabled: true
  image:
    repository: grafana/loki
    tag: "latest"
  service:
    type: ClusterIP
    port: 3100
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
alertmanager:
  enabled: true
  image:
    repository: prom/alertmanager
    tag: "latest"
  service:
    type: ClusterIP
    port: 9093
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"