apiVersion: v1
global:
  image:
    repository: grafana/grafana
    tag: "latest"
grafana:
  enabled: true
  admin:
    adminUser: admin
    adminPassword: admin
  service:
    type: ClusterIP
    port: 3000
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
