prometheus:
  replicaCount: 1
  image:
    repository: prom/prometheus
    tag: v2.41.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9090
  pvc:
    storageClass: default
    size: 10Gi

grafana:
  replicaCount: 1
  image:
    repository: grafana/grafana
    tag: 9.3.2
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000
  ingress:
    enabled: true
    hostname: grafana.example.com

loki:
  replicaCount: 1
  image:
    repository: grafana/loki
    tag: 2.6.1
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3100
  pvc:
    storageClass: default
    size: 10Gi

alertmanager:
  replicaCount: 1
  image:
    repository: prom/alertmanager
    tag: v0.25.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9093
