apiVersion: v1
global:
  environment: production
  domain: fledxy.com

grafana:
  image:
    repository: grafana/grafana
    tag: "latest"
    pullPolicy: IfNotPresent
  admin:
    adminUser: admin
    adminPassword: admin
  service:
    type: ClusterIP
    port: 3000
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - grafana.fledxy.com
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.fledxy.com

loki:
  enabled: true
  image:
    repository: grafana/loki
    tag: "2.9.2"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3100
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  storage:
    type: filesystem
    retention:
      enabled: false
      period: "168h"
