apiVersion: v1
global:
  environment: production
  domain: fledxy.com

prometheus:
  enabled: true
  image:
    repository: prom/prometheus
    tag: "v2.45.0"
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  service:
    type: ClusterIP
    port: 9090
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - prometheus.fledxy.com
    tls:
      - secretName: prometheus-tls
        hosts:
          - prometheus.fledxy.com
  storage:
    type: emptyDir
    sizeLimit: 10Gi
  retention: 15d
  scrapeInterval: 15s
  evaluationInterval: 15s
  global:
    scrape_interval: 15s
    evaluation_interval: 15s
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"
  ruleFiles:
    - /etc/prometheus/rules/*.yaml
  additionalScrapeConfigs:
    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name

grafana:
  enabled: true
  image:
    repository: grafana/grafana
    tag: "latest"
    pullPolicy: IfNotPresent
  admin:
    adminUser: admin
    adminPassword: admin
  service:
    type: ClusterIP
    port: 3001
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - grafana.fledxy.com
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.fledxy.com
  rbac:
    create: true
    pspEnabled: false
  securityContext:
    runAsUser: 472
    runAsGroup: 472
    fsGroup: 472

loki:
  enabled: true
  mode: SingleBinary
  singleBinary:
    enabled: true
  image:
    repository: grafana/loki
    tag: "2.9.2"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3100
    grpcPort: 9096
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  storage:
    type: filesystem
    persistence:
      enabled: false
    filesystem:
      enabled: true
      size: 10Gi
  limits:
    ingestion_rate_mb: 4
    ingestion_burst_size_mb: 6
    max_query_series: 500
    max_query_lookback: 168h
    max_query_length: 721h
    max_query_parallelism: 32
    cardinality_limit: 100000
    split_queries_by_interval: 15m

fluentbit:
  enabled: true
  image:
    repository: fluent/fluent-bit
    tag: "1.9.9"
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: "200Mi"
      cpu: "100m"
    limits:
      memory: "500Mi"
      cpu: "500m"
  config:
    service:
      flush: 5
      daemon: "off"
      log_level: "info"
      http_server: "on"
      http_listen: "0.0.0.0"
      http_port: "2020"
    inputs:
      - name: tail
        path: /var/log/containers/*.log
        parser: docker
        tag: kube.*
        mem_buf_limit: 5MB
        skip_long_lines: "on"
        refresh_interval: 10
    filters:
      - name: kubernetes
        match: kube.*
        merge_log: "on"
        keep_log: "off"
        k8s_logging_parser: "on"
    outputs:
      - name: loki
        match: kube.*
        host: loki
        port: 3100
        labels:
          - job=fluent-bit
          - namespace=$kubernetes['namespace_name']
          - pod=$kubernetes['pod_name']
          - container=$kubernetes['container_name']
