apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-annotations
data:
  prometheus-annotations.yaml: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      template:
        metadata:
          labels:
            app: backend
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "8080"
            prometheus.io/path: "/metrics"
        spec:
          containers:
          - name: backend
            ports:
            - containerPort: 8080
              name: metrics
            livenessProbe:
              httpGet:
                path: /metrics
                port: 8080
            readinessProbe:
              httpGet:
                path: /metrics
                port: 8080
