apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
{{- if eq .Values.prometheus.service.type "LoadBalancer" }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "false"
{{- end }}
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
    - port: {{ .Values.prometheus.service.port }}
      targetPort: 9090
      protocol: TCP
  selector:
    app: prometheus 