apiVersion: v1
kind: Service
metadata:
  name: loki
spec:
  type: {{ .Values.loki.service.type }}
  ports:
    - port: {{ .Values.loki.service.port }}
      targetPort: {{ .Values.loki.service.port }}
  selector:
    app: loki
