apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: benefits-dev
data:
  FLASK_ENV: "production"
  FLASK_DEBUG: "false"
  PORT: "5000"
  DB_NAME: "benefits_db"
  DB_USER: "benefits"
  DB_PASSWORD: "postgres"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  CORS_ORIGINS: "fledxy.cloud"
  DB_POOL_SIZE: "20"
  DB_MAX_OVERFLOW: "10"
  DB_POOL_TIMEOUT: "30"
  DB_POOL_RECYCLE: "3600"
  DB_POOL_PRE_PING: "true" 
