# Elasticsearch configuration
replicaCount: 3

esConfig:
  elasticsearch.yml: |
    cluster.name: "benefits-cluster"
    network.host: 0.0.0.0
    xpack.security.enabled: true

resources:
  requests:
    cpu: "300m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

# Disable persistence and use emptyDir
persistence:
  enabled: false

service:
  type: ClusterIP
  port: 9200

# Security configuration
securityContext:
  runAsUser: 1000
  fsGroup: 1000
