# Elasticsearch configuration
replicaCount: 1

esConfig:
  elasticsearch.yml: |
    cluster.name: "benefits-cluster"
    network.host: 0.0.0.0
    discovery.type: single-node
    xpack.security.enabled: true

resources:
  requests:
    cpu: "300m"
    memory: "512Mi"
  limits:
    cpu: "500m"
    memory: "1Gi"

persistence:
  enabled: true
  size: 10Gi
  storageClass: "gp2"

service:
  type: ClusterIP
  port: 9200

# Security configuration
securityContext:
  runAsUser: 1000
  fsGroup: 1000

# Enable volume expansion
volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 20Gi
  storageClassName: "gp2" 