# Loki configuration
loki:
  auth_enabled: false
  storage:
    type: filesystem
    persistentVolumeClaim:
      enabled: true
      size: 5Gi
      storageClassName: "gp3-csi"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

promtail:
  enabled: true
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "100m"
      memory: "128Mi" 