{{- if .Values.alertmanager.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-alertmanager
  namespace: {{ .Release.Namespace }}
  labels:
    app: alertmanager
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.alertmanager.replicaCount }}
  selector:
    matchLabels:
      app: alertmanager
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: alertmanager
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: alertmanager
          image: "{{ .Values.alertmanager.image.repository }}:{{ .Values.alertmanager.image.tag }}"
          imagePullPolicy: {{ .Values.alertmanager.image.pullPolicy }}
          args:
            - "--config.file=/etc/alertmanager/alertmanager.yml"
            - "--storage.path=/alertmanager"
          ports:
            - name: http
              containerPort: 9093
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager
            - name: storage
              mountPath: /alertmanager
          resources:
            {{- toYaml .Values.alertmanager.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-alertmanager-config
        - name: storage
          {{- if .Values.alertmanager.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-alertmanager
          {{- else }}
          emptyDir: {}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-alertmanager
  namespace: {{ .Release.Namespace }}
  labels:
    app: alertmanager
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.alertmanager.service.type }}
  ports:
    - port: 9093
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: alertmanager
    release: {{ .Release.Name }}
{{- end }} 