{{- if .Values.loki.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-loki
  namespace: {{ .Release.Namespace }}
  labels:
    app: loki
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.loki.replicaCount }}
  selector:
    matchLabels:
      app: loki
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: loki
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: loki
          image: "{{ .Values.loki.image.repository }}:{{ .Values.loki.image.tag }}"
          imagePullPolicy: {{ .Values.loki.image.pullPolicy }}
          args:
            - "-config.file=/etc/loki/loki.yaml"
          ports:
            - name: http
              containerPort: 3100
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: storage
              mountPath: /tmp/loki
          resources:
            {{- toYaml .Values.loki.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ .Release.Name }}-loki-config
        - name: storage
          {{- if .Values.loki.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-loki
          {{- else }}
          emptyDir: {}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-loki
  namespace: {{ .Release.Namespace }}
  labels:
    app: loki
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.loki.service.type }}
  ports:
    - port: 3100
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: loki
    release: {{ .Release.Name }}
{{- end }} 