apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: monitoring
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        5
        Log_Level    info
        Daemon       off
        HTTP_Server  on
        HTTP_Listen  0.0.0.0
        HTTP_Port    2020

    @INCLUDE input-kubernetes.conf
    @INCLUDE output-loki.conf
    @INCLUDE output-cloudwatch.conf

  input-kubernetes.conf: |
    [INPUT]
        Name             tail
        Path             /var/log/containers/*.log
        Parser           docker
        Tag              kube.*
        Refresh_Interval 5
        Mem_Buf_Limit    5MB
        Skip_Long_Lines  On
        DB               /var/log/flb_kube.db
        Live_Tail        On

  output-loki.conf: |
    [OUTPUT]
        Name loki
        Match kube.*
        Url http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
        LabelmapPath /fluent-bit/etc/labelmap.json

  output-cloudwatch.conf: |
    [OUTPUT]
        Name cloudwatch_logs
        Match kube.*
        region ${{ secrets.AWS_REGION }}
        log_group_name /aws/eks/{{cluster_name}}/containerlogs
        log_stream_name {{namespace}}-{{pod_name}}
        auto_create_group true

  labelmap.json: |
    {
        "kubernetes": {
            "container_name": "container",
            "host": "node_name"
        }
    } 