apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
spec:
  storageClassName: {{ .Values.loki.pvc.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.loki.pvc.size }}
