apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
data:
  loki.yaml: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    common:
      instance_store: 'boltdb'
      path_prefix: /tmp/loki
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    schema_config:
      configs:
        - from: 2020-10-27
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    # By default, Loki will use inmemory index and boltdb-shipper store.
    # For production use, consider using object storage like S3 or GCS and a robust index store like Cassandra or Bigtable.
    storage_config:
      boltdb_shipper:
        activeindexdirectory: /tmp/loki/boltdb-shipper-active
        cachelocation: /tmp/loki/boltdb-shipper-cache
        resyncinterval: 5s
      filesystem:
        directory: /tmp/loki/chunks

    ingester:
      lifecycletime: 5m
      chunkidleperiod: 5m
      chunkretainperiod: 30s
      maxchunkage: 5m
      chunktargetsize: 1048576 # 1MB
      maxpostsize: 4194304 # 4MB

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h # 7 days

    # Recommended: enable these for production use
    # ruler:
    #   storage:
    #     type: local
    #     local:
    #       directory: /tmp/loki/rules
    #   ring:
    #     kvstore:
    #       store: inmemory
    #   rule_path: /tmp/loki/rules-temp
    #   alertmanager_url: http://alertmanager.monitoring.svc.cluster.local:9093
    #   enable_api: true
    #   enable_runtime_config: true

    # alerting:
    #   alertmanagers:
    #     - http_client:
    #         bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    #         tls_config:
    #           insecure_skip_verify: true
    #       scheme: http
    #       timeout: 10s
    #       api_version: v2
    #       static_configs:
    #         - <alertmanager_service_name>.<namespace>.svc.cluster.local:9093

    # query_range:
    #   align_queries_with_step: true
    #   max_query_lookback: 7d

    # analyze:
    #   max_query_lookback: 7d

    # frontend:
    #   max_outstanding_per_tenant: 200

    # distributor:
    #   ring:
    #     kvstore:
    #       store: inmemory

    # compactor:
    #   working_directory: /tmp/loki/compactor
    #   compaction_interval: 10m

    # index_gateway:
    #   ring:
    #     kvstore:
    #       store: inmemory

    # ingester_client:
    #   grpc_client_config:
    #     max_recv_msg_size: 4194304
    #     max_send_msg_size: 4194304

    # store_gateway:
    #   client:
    #     grpc_client_config:
    #       max_recv_msg_size: 4194304
    #       max_send_msg_size: 4194304

    # table_manager:
    #   retention_deletes_enabled: false # Recommended: set to true for production
    #   retention_period: 7d # Example retention period

    # usage_stats:
    #   enabled: true
    #   filemode: 0644
    #   filename: /tmp/loki/usage.log

    # tracing:
    #   jaeger:
    #     agent_host_port: jaeger-agent.monitoring.svc.cluster.local:6831
    #     collector_endpoint: http://jaeger-collector.monitoring.svc.cluster.local:14268/api/traces 