apiVersion: v1
kind: ServiceAccount
metadata:
  name: ebs-csi-controller-sa
  labels:
    app.kubernetes.io/name: aws-ebs-csi-driver
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::376129850044:role/amazoneks_ebs_csi_driver_role