global:
  environment: production
  domain: example.com

server:
  name: argocd-server
  replicas: 1
  image:
    repository: argoproj/argocd
    tag: v2.7.4
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  service:
    type: ClusterIP
    port: 80
    portHttps: 443
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    hosts:
      - argocd.example.com
    tls:
      - secretName: argocd-server-tls
        hosts:
          - argocd.example.com

repoServer:
  name: argocd-repo-server
  replicas: 1
  image:
    repository: argoproj/argocd
    tag: v2.7.4
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

applicationSet:
  enabled: true
  image:
    repository: argoproj/argocd
    tag: v2.7.4
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

configs:
  secret:
    argocdServerAdminPassword: "$2a$10$mz3tF3c5Ux5x5x5x5x5x5O5x5x5x5x5x5x5x5x5x5x5x5x5x5" # bcrypt hash of "admin"
  cm:
    url: https://argocd.example.com
    admin.enabled: "true"
    statusbadge.enabled: "true"
    application.instanceLabelKey: argocd.argoproj.io/instance
    resource.customizations: |
      argoproj.io/Application:
        health.lua: |
          health_status = {}
          if obj.status ~= nil then
            if obj.status.health ~= nil then
              health_status.status = obj.status.health.status
              if obj.status.health.message ~= nil then
                health_status.message = obj.status.health.message
              end
            end
          end
          return health_status
  rbac:
    policy.default: role:readonly
    policy.csv: |
      p, role:org-admin, applications, *, */*, allow
      p, role:org-admin, clusters, get, *, allow
      p, role:org-admin, projects, get, *, allow
      p, role:org-admin, repositories, get, *, allow
      p, role:org-admin, logs, get, */*, allow
      p, role:org-admin, exec, create, */*, allow
      p, role:org-admin, applications, create, */*, allow
      p, role:org-admin, applications, update, */*, allow
      p, role:org-admin, applications, delete, */*, allow
      p, role:org-admin, applications, sync, */*, allow
      p, role:org-admin, applications, override, */*, allow
      p, role:org-admin, applications, action/*, */*, allow
      p, role:org-admin, clusters, create, *, allow
      p, role:org-admin, clusters, update, *, allow
      p, role:org-admin, clusters, delete, *, allow
      p, role:org-admin, projects, create, *, allow
      p, role:org-admin, projects, update, *, allow
      p, role:org-admin, projects, delete, *, allow
      p, role:org-admin, repositories, create, *, allow
      p, role:org-admin, repositories, update, *, allow
      p, role:org-admin, repositories, delete, *, allow

redis:
  enabled: true
  image:
    repository: redis
    tag: 7.0.11-alpine
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

notifications:
  enabled: true
  image:
    repository: argoproj/argocd
    tag: v2.7.4
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

dex:
  enabled: true
  image:
    repository: ghcr.io/dexidp/dex
    tag: v2.35.3
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

rbac:
  enabled: true
  create: true

serviceAccount:
  create: true
  name: argocd-application-controller
  annotations: {}

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80 