version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - benefits-network
    restart: unless-stopped

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=benefits_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - benefits-network
    restart: unless-stopped

networks:
  benefits-network:
    driver: bridge

volumes:
  postgres_data: 