apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
data:
  local-config.yaml: |
    auth_enabled: false
    server:
      http_listen_port: 3100
      grpc_listen_port: 9096
    common:
      path_prefix: /loki
      storage:
        inmemory:
          max_chunk_age: 2h
      replication_factor: 1
    schema_config:
      configs:
        - from: 2020-05-15
          store: inmemory
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h
    storage_config:
      filesystem:
        directory: /loki/chunks
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      ingestion_rate_mb: 4
      ingestion_burst_size_mb: 6
      max_query_series: 500
      split_queries_by_interval: 15m
    chunk_store_config:
      max_look_back_period: 24h
    querier:
      align_queries_with_step: true
      max_query_length: 12h
      max_entries_limit: 500000
      max_entries_limit_per_series: 50000
    ingester:
      chunk_idle_period: 1h
      chunk_retain_period: 10m
      max_chunk_age: 1h
      chunk_target_size: 1500000
      chunk_encoding: snappy