apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
  labels:
    app: loki
spec:
  ports:
    - port: {{ .Values.loki.service.port }}
      targetPort: {{ .Values.loki.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: loki 