name: Build, Push and Deploy to Kubernetes

on:
  push:
    branches:
      - main # Trigger action on pushes to main branch
      - dev
    # paths-ignore:
    #   - "k8s/**"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout repository
         uses: actions/checkout@v3

       - name: Set up Python
         uses: actions/setup-python@v4
         with:
           python-version: '3.x'
   
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
   
       - name: Log in to Docker container Registry
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}

       - name: Build Docker image backend
         run: |
             docker build -f benefits.dev/backend/app.Dockerfile  -t fledxy/benefits-backend:${{ github.sha }} ./benefits.dev/backend
             
       - name: Build Docker image frontend
         run: |
             docker build -f benefits.dev/frontend/app.Dockerfile  -t fledxy/benefits-frontend:${{ github.sha }} ./benefits.dev/frontend
             
       - name: Push Docker images to Docker hub
         run: |
             docker push fledxy/benefits-backend:${{ github.sha }}
             docker push fledxy/benefits-frontend:${{ github.sha }}

       - name: Tag Docker image as latest
         run: |
             docker tag fledxy/benefits-backend:${{ github.sha }} fledxy/benefits-backend:latest
             docker tag fledxy/benefits-frontend:${{ github.sha }} fledxy/benefits-frontend:latest

  deploy-infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app.tf

    steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }} 

        - name: Terraform init
          run: terraform init -upgrade

        - name: Terraform plan for environment 
          run: terraform plan --var-file=envs/${{ github.ref_name }}.tfvars

        - name: Terraform apply for environment 
          run: terraform apply -auto-approve --var-file=envs/${{ github.ref_name }}.tfvars
  
  deploy-to-eks:
    needs: [build, deploy-infra]
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Set up JDK 17 
          uses: actions/setup-java@v3
          with: 
            java-version: '17'
            distribution: 'temurin'

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }} 

        - name: SonarQube Scan
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          run: |
              wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
              unzip sonar-scanner-cli-5.0.1.3006-linux.zip
              export PATH="$PATH:$(pwd)/sonar-scanner-5.0.1.3006-linux/bin"
              sonar-scanner \
                -Dsonar.projectKey=fledxy_benefits_aws\
                -Dsonar.organization=fledxy \
                -Dsonar.sources=. \
                -Dsonar.host.url=https://sonarcloud.io \
                -Dsonar.login=$SONAR_TOKEN

        - name: Access to eks cluster
          run: |
              aws eks create-access-entry --cluster-name ${{ secrets.EKS_CLUSTER_NAME }} --principal-arn ${{ secrets.AWS_USER_ARN }} --type STANDARD --user ${{ secrets.AWS_USERNAME }} --kubernetes-groups Viewers --region ${{ secrets.AWS_REGION }}

              aws eks associate-access-policy --cluster-name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }} --principal-arn ${{ secrets.AWS_USER_ARN }}  --access-scope type=cluster  --policy-arn arn:aws:eks::aws:cluster-access-policy/AmazonEKSClusterAdminPolicy

        - name: Update kube config
          run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}
        
        - name: Create namespace for branch
          run: |
            kubectl create namespace benefits-${{ github.ref_name }} --dry-run=client -o yaml | kubectl apply -f -
            
        - name: Deploy PostgreSQL using Helm
          run: |
            helm uninstall postgres --namespace benefits-${{ github.ref_name }} || true
            
            # Install PostgreSQL with dynamic namespace
            helm install postgres k8s/postgres \
              --namespace benefits-${{ github.ref_name }} \
              -f k8s/postgres/values.yaml \
              --set postgresql.database=benefits_db \
              --set postgresql.username=benefits \
              --set postgresql.password=postgres \
              --set persistence.enabled=true
            
        - name: Create database connection secret
          run: |
            # Create secrets for database connection
            kubectl create secret generic db-secrets \
              --from-literal=POSTGRES_DB=benefits_db \
              --from-literal=POSTGRES_USER=benefits \
              --from-literal=POSTGRES_PASSWORD=postgres \
              -n benefits-${{ github.ref_name }}
        - name: Deploy Backend using Kustomize
          run: |
            cd k8s/backend
            kustomize edit set namespace benefits-${{ github.ref_name }}
            kustomize edit set image fledxy/fledxy_application=fledxy/benefits-backend:${{ github.sha }}
            sed -i "s|CORS_ORIGINS:.*|CORS_ORIGINS: \"https://api.fledxy.cloud\"|" configmap.yaml
            kubectl apply -k .
            
        - name: Deploy Frontend using Kustomize
          run: |
            cd k8s/frontend
            kustomize edit set namespace benefits-${{ github.ref_name }}
            kustomize edit set image fledxy/fledxy_application=fledxy/benefits-frontend:${{ github.sha }}
            sed -i "s|REACT_APP_API_URL:.*|REACT_APP_API_URL: \"https://fledxy.cloud\"|" configmap.yaml
            kubectl apply -k .
        
        - name: Deploy Ingress and Network Policy
          run: |
          
            # Apply ingress and network policy
            kubectl apply -f k8s/ingress.yaml --namespace benefits-${{ github.ref_name }}
            kubectl apply -f k8s/network-policy.yaml --namespace benefits-${{ github.ref_name }}

        - name: Deploy ArgoCD
          run: |
            kubectl create namespace argocd
            helm repo add argo https://argoproj.github.io/argo-helm
            helm upgrade --install argocd argo/argo-cd \
              -f k8s/argocd/values.yaml \
              --namespace argocd \
              --create-namespace

  monitoring:
    needs: [build, deploy-infra, deploy-to-eks]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kube config
        run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Create monitoring namespace
        run: kubectl create namespace monitoring

      - name: Update monitoring chart values
        run: |
          # Set domain based on branch
          if [ "${{ github.ref_name }}" = "main" ]; then
            DOMAIN="fledxy.com"
          else
            DOMAIN="dev.fledxy.com"
          fi
          
          # Update values.yaml with environment-specific settings
          sed -i "s/domain: fledxy.com/domain: $DOMAIN/" k8s/monitoring/values.yaml
          sed -i "s/grafana.fledxy.com/grafana.$DOMAIN/" k8s/monitoring/values.yaml
          
          # Update Grafana admin credentials
          sed -i "s/adminPassword: admin/adminPassword: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}/" k8s/monitoring/values.yaml

      - name: Install monitoring stack
        run: |
          helm uninstall monitoring --namespace monitoring || true
          helm upgrade --install monitoring ./k8s/monitoring --namespace monitoring

  testing:
    needs: [build, deploy-infra, deploy-to-eks, monitoring]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kube config
        run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Test Application and Monitoring
        run: |
          # Kiểm tra namespace
          echo "\nChecking application namespace..."
          kubectl get namespace

          # Kiểm tra pods của ứng dụng
          echo "\nChecking application pods..."
          kubectl get pods -n benefits-${{ github.ref_name }}
          kubectl get pods -n monitoring
          kubectl get pods -n argocd

          # Kiểm tra services
          echo "\nChecking services..."
          kubectl get svc -n benefits-${{ github.ref_name }}
          kubectl get svc -n monitoring
          kubectl get svc -n argocd
