name: Build, Push and Deploy to Kubernetes

on:
  push:
    branches:
      - dev 
      - main # Trigger action on pushes to main branch

jobs:
  build:
    runs-on: ubuntu:lastest

    # steps:
    #    - name: Checkout repository
    #      uses: actions/checkout@v3
  deploy:
    runs-on: ubuntu:lastest

