  name: Deploy Infrastructure
  on:
    push:
      branches:
        - main
  jobs:
    deploy-infra:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: app.tf
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }} 

            - name: Terraform init
              run: terraform init -upgrade

            - name: Terraform plan for environment 
              run: terraform plan --var-file=envs/${{ github.ref_name }}.tfvars

            - name: Terraform apply for environment 
              run: terraform apply -auto-approve --var-file=envs/${{ github.ref_name }}.tfvars