name: Terraform Destroy Infrastructer

on:
  workflow_dispatch:
    inputs: 
      confirmation: 
        description: 'Type "Confirm" to destroy all the terraform infrastructure resources'
        required: true 
        default: '' 

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }} #get correct the environment <dev or main >
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} 
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform destroy
        if: ${{ inputs.confirmation == 'Confirm' }}
        run: |
            cd app.tf
            terraform init -backend-config=${{github.ref_name}}.conf
            terraform destroy -var-file=envs/${{github.ref_name}}.tfvars --auto-approve
            cd ..
          
      - name: Check Confirmation
        if: github.event.inputs.confirmation != 'Confirm'
        run: |
            echo "not provided"
            exit 1
